import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './common/http-exception.filter';
import { version, license } from '../package.json';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    logger: ['error', 'warn', 'log'],
  });
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
    }),
  );
  app.useGlobalFilters(new HttpExceptionFilter());
  app.set('trust proxy', 1);

  // OPEN API document
  const config = new DocumentBuilder()
    .setTitle('monacardjs - REST API docs')
    .setDescription(
      `Documentation for monacardjs API. This document is generated by swagger UI<br>
      Monacardjs APIのドキュメントです。このドキュメントはswagger UIによって作成されました。
      `,
    )
    .setLicense(
      license,
      'https://github.com/ocknamo/monacardjs/blob/main/LICENCE',
    )
    .setVersion(version)
    .addTag('utilities')
    .addTag('monacard1.0')
    .addTag('IPFS')
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api', app, document);

  await app.listen(3000);
}
bootstrap();
